version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/lemon4ksan/aoni)

    gofumpt:
      module-path: github.com/lemon4ksan/aoni
      extra:
        group-params: true

    goimports:
      local-prefixes:
        - github.com/lemon4ksan/aoni

    golines:
      max-len: 120

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - bodyclose
    - nilerr
    - noctx
    - errorlint
    - protogetter
    - gocritic
    - prealloc
    - perfsprint
    - gosec
    - wsl_v5
    - depguard

  settings:
    depguard:
      rules:
        root-isolation:
          files:
            - "$root/*.go"
          deny:
            - pkg: "unsafe"
              desc: "Package aoni must not import unsafe directly. All dirty hacks must be in /internal/ or /fast/."
            - pkg: "sync"
              desc: "Package aoni must not import sync directly to avoid sync.Pool usage."

    revive:
      rules:
        - name: exported
          disabled: true

    wsl_v5:
      default: default
      allow-first-in-block: true
      allow-whole-block: true
      branch-max-lines: 3
      case-max-lines: 5
      enable:
        - leading-whitespace
        - trailing-whitespace
        - after-block
        - err

  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - linters: [errcheck, revive, staticcheck, protogetter]
        path: .*(pb\.go|generated\.go)

      - linters: [staticcheck]
        text: "SA1019: .*golang.org/x/net/http2"

      - linters: [gosec]
        text: "G103:"

      - linters: [gosec]
        text: "G404:"

      - linters: [gosec]
        text: "G115:"

      - linters: [gosec]
        text: "G306:|G301:"

      - linters: [revive]
        path: "_test\\.go"
        text: "exported: (exported|comment on exported)"

      - linters: [gosec, noctx, bodyclose, errcheck, prealloc]
        path: "_test\\.go"

      - linters: [gosec]
        text: "G703:|G706:"
        path: "(cmd|examples)/.*"

    paths:
      - "examples/.*"
      - "tests/.*"
      - "internal/fast/h1engine/.*"
