// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// protoc-gen-aoni is a plugin for the Protobuf compiler (protoc) that generates
// zero-allocation, uTLS-stealthy gRPC clients targeting the aoni/grpc package.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"

	"github.com/lemon4ksan/aoni"
)

var (
	contextPackage = protogen.GoImportPath("context")
	aoniPackage    = protogen.GoImportPath("github.com/lemon4ksan/aoni")
	grpcPackage    = protogen.GoImportPath("github.com/lemon4ksan/aoni/grpc")

	generatedFilenameExtension = "_aoni.pb.go"
)

func main() {
	showVersion := flag.Bool("version", false, "print the version and exit")

	flag.Parse()

	if *showVersion {
		fmt.Printf("protoc-gen-aoni %v\n", aoni.Version)
		os.Exit(0)
	}

	var flags flag.FlagSet

	protogen.Options{
		ParamFunc: flags.Set,
	}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(
			pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL,
		) | uint64(
			pluginpb.CodeGeneratorResponse_FEATURE_SUPPORTS_EDITIONS,
		)
		gen.SupportedEditionsMinimum = descriptorpb.Edition_EDITION_PROTO2
		gen.SupportedEditionsMaximum = descriptorpb.Edition_EDITION_2024

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}

			generateFile(gen, f)
		}

		return nil
	})
}

// generateFile generates a _aoni.pb.go file containing aoni gRPC service client definitions.
func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Services) == 0 {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + generatedFilenameExtension
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	programName := filepath.Base(os.Args[0])
	if ext := filepath.Ext(programName); strings.EqualFold(ext, ".exe") {
		programName = strings.TrimSuffix(programName, ext)
	}

	g.P("// Code generated by ", programName, ". DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - ", programName, " v", aoni.Version)
	g.P("// - protoc           ", protocVersion(gen))

	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}

	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	generateFileContent(gen, file, g)

	return g
}

func protocVersion(gen *protogen.Plugin) string {
	v := gen.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}

	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}

	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

func generateFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	for _, service := range file.Services {
		genService(gen, file, g, service)
	}
}

func genService(_ *protogen.Plugin, _ *protogen.File, g *protogen.GeneratedFile, service *protogen.Service) {
	// Full methods constants.
	genFullMethods(g, service)

	clientName := service.GoName + "Client"

	g.P("// ", clientName, " is the aoni stealth gRPC client API for ", service.GoName, " service.")
	g.AnnotateSymbol(clientName, protogen.Annotation{Location: service.Location})
	g.P("type ", clientName, " interface {")

	for _, method := range service.Methods {
		g.AnnotateSymbol(clientName+"."+method.GoName, protogen.Annotation{Location: method.Location})
		g.P(method.Comments.Leading, clientSignature(g, method))
	}

	g.P("}")
	g.P()

	// Client struct.
	implName := unexport(clientName)
	g.P("type ", implName, " struct {")
	g.P("doer ", aoniPackage.Ident("RequestDoer"))
	g.P("}")
	g.P()

	// NewClient constructor.
	g.P("func New", clientName, "(doer ", aoniPackage.Ident("RequestDoer"), ") ", clientName, " {")
	g.P("return &", implName, "{doer: doer}")
	g.P("}")
	g.P()

	// Client method implementations.
	for _, method := range service.Methods {
		genClientMethod(g, service, method)
	}
}

func genFullMethods(g *protogen.GeneratedFile, service *protogen.Service) {
	if len(service.Methods) == 0 {
		return
	}

	g.P("const (")

	for _, method := range service.Methods {
		fmSymbol := formatFullMethodSymbol(service, method)
		fmName := fmt.Sprintf("/%s/%s", service.Desc.FullName(), method.Desc.Name())
		g.P(fmSymbol, ` = "`, fmName, `"`)
	}

	g.P(")")
	g.P()
}

func formatFullMethodSymbol(service *protogen.Service, method *protogen.Method) string {
	return fmt.Sprintf("%s_%s_FullMethodName", service.GoName, method.GoName)
}

func clientSignature(g *protogen.GeneratedFile, method *protogen.Method) string {
	s := method.GoName + "(ctx " + g.QualifiedGoIdent(contextPackage.Ident("Context"))
	s += ", in *" + g.QualifiedGoIdent(method.Input.GoIdent)
	s += ", mods ..." + g.QualifiedGoIdent(aoniPackage.Ident("RequestModifier")) + ") ("

	if !method.Desc.IsStreamingServer() && !method.Desc.IsStreamingClient() {
		s += "*" + g.QualifiedGoIdent(method.Output.GoIdent)
	} else {
		s += "*" + g.QualifiedGoIdent(
			grpcPackage.Ident("StreamResponse"),
		) + "[" + g.QualifiedGoIdent(
			method.Output.GoIdent,
		) + "]"
	}

	s += ", error)"

	return s
}

func genClientMethod(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method) {
	implName := unexport(service.GoName + "Client")
	fmSymbol := formatFullMethodSymbol(service, method)

	g.P("func (c *", implName, ") ", clientSignature(g, method), " {")

	if !method.Desc.IsStreamingServer() && !method.Desc.IsStreamingClient() {
		g.P(
			"return ",
			grpcPackage.Ident("Invoke"),
			"[",
			method.Output.GoIdent,
			"](ctx, c.doer, ",
			fmSymbol,
			", in, mods...)",
		)
	} else {
		g.P(
			"return ",
			grpcPackage.Ident("ServerStream"),
			"[",
			method.Output.GoIdent,
			"](ctx, c.doer, ",
			fmSymbol,
			", in, mods...)",
		)
	}

	g.P("}")
	g.P()
}

func unexport(s string) string {
	if s == "" {
		return ""
	}

	return strings.ToLower(s[:1]) + s[1:]
}
